apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: svc
  name: svc
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: svc:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/glroland/sudoku.git
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: ARTIFACT_DIR
        value: sudoku-svc/target/
      - name: MODULE_DIR
        value: sudoku-svc
      from:
        kind: ImageStreamTag
        name: java:8
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - imageChange:
    type: ImageChange
  - type: ConfigChange
