apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    name: ocr-svc
  name: ocr-svc
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: ocr-svc:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: sudoku-ocr-svc
    git:
      uri: https://github.com/glroland/sudoku.git
    type: Git
  strategy:
    dockerStrategy:
      env:
      - name: EXAMPLE
        value: sample-app
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
