apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: app
  name: app
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: app:latest
  postCommit: {}
  resources:
    limits:
      cpu: '1'
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 10Mi
  runPolicy: Serial
  source:
    contextDir: sudoku-app
    git:
      uri: https://github.com/glroland/sudoku.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:10
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - imageChange:
    type: ImageChange
  - type: ConfigChange
