apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  creationTimestamp: "2021-07-08T17:57:23Z"
  labels:
    template: postgresql-persistent-template
    template.openshift.io/template-instance-owner: 8ee27071-04f7-43ee-b3ae-a8ab96804204
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:database-name: {}
        f:database-password: {}
        f:database-user: {}
      f:metadata:
        f:annotations:
          .: {}
          f:template.openshift.io/expose-database_name: {}
          f:template.openshift.io/expose-password: {}
          f:template.openshift.io/expose-username: {}
        f:labels:
          .: {}
          f:template: {}
          f:template.openshift.io/template-instance-owner: {}
      f:type: {}
    manager: openshift-controller-manager
    operation: Update
    time: "2021-07-08T17:57:23Z"
  name: postgresql
type: Opaque
data:
  database-name: c3Vkb2t1X2Ri
  database-password: cGFzc3dvcmQx
  database-user: c3Vkb2t1
