apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sudoku.fullname" . }}
  labels:
    {{- include "sudoku.labels" . | nindent 4 }}
data:
  application.properties: |-
    # quarkus application configuration
    quarkus.package.type=uber-jar
    quarkus.http.port=8080
    quarkus.swagger-ui.always-include=true

    # datasource configuration
    quarkus.datasource.db-kind = postgresql
    quarkus.datasource.username = sudoku
    quarkus.datasource.password = password1
    quarkus.datasource.jdbc.url = jdbc:postgresql://{{ include "sudoku.fullname" . }}-pgsql:5432/sudoku_db
    #quarkus.hibernate-orm.database.generation=drop-and-create
    quarkus.hibernate-orm.database.generation=update
