apiVersion: v1
kind: Service
metadata:
  name: {{ include "sudoku.fullname" . }}-pgsql
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: {{ include "sudoku.fullname" . }}-pgsql
  sessionAffinity: None
  type: ClusterIP
