apiVersion: v1
kind: ConfigMap
metadata:
  name: svc-config
data:
  application.properties: |-
    gamelog.url=http://log-svc:8080
    gamelog.failOnError=false
---
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: svc
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc
spec:
  selector:
    matchLabels:
      app: svc
  replicas: 3
  template:
    metadata:
      labels:
        app: svc
    spec:
      containers:
      - name: svc
        image: svc:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
        env:
          - name: JAVA_OPTS_APPEND
            value: '-Dlogging.level.root=INFO'
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /deployments/config
          name: application-properties
          readOnly: true
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - configMap:
          defaultMode: 511
          items:
          - key: application.properties
            path: application.properties
          name: svc-config
        name: application-properties
