apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sudoku.fullname" . }}
  labels:
    {{- include "sudoku.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - {{ include "sudoku.fullname" . }}.{{ .Values.ingress.url }}
      secretName: {{ include "sudoku.fullname" . }}-cert
  rules:
    - host: {{ include "sudoku.fullname" . }}.{{ .Values.ingress.url }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              service:
                name: {{ include "sudoku.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
            pathType: Prefix
