apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "sudoku.fullname" . }}
  labels:
    {{- include "sudoku.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        - {{ include "sudoku.fullname" . }}{{ .Values.ingress.url }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ include "sudoku.fullname" . }}.{{ .Values.ingress.url }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ include "sudoku.fullname" . }}
              servicePort: {{ .Values.service.port }}
            pathType: Prefix
