kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "sudoku.fullname" . }}
  labels:
    app.kubernetes.io/part-of: "{{ .Release.Name }}-sudoku"
    {{- include "sudoku.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ include "sudoku.fullname" . }}"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sudoku.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgresql
          image: 'registry.redhat.io/rhel9/postgresql-16@sha256:1c65c89c880228f8526ac359556419eaa4a691246b78a4ab543c61394f7e7888'
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_USER
              value: sudoku
            - name: POSTGRESQL_PASSWORD
              value: sudoku123
            - name: POSTGRESQL_DATABASE
              value: sudoku_db
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
