apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  finalizers:
    - postgres-operator.crunchydata.com/finalizer
  name: {{ include "sudoku.fullname" . }}
  labels:
    app.kubernetes.io/part-of: "{{ .Release.Name }}-sudoku"
    {{- include "sudoku.labels" . | nindent 4 }}
spec:
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      name: instance1
      replicas: 1
  port: 5432
  postgresVersion: 14
