apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sudoku.fullname" . }}
  labels:
    {{- include "sudoku.labels" . | nindent 4 }}
type: Opaque
data:
  database-name: c3Vkb2t1X2Ri
  database-password: cGFzc3dvcmQx
  database-user: c3Vkb2t1
