apiVersion: v1
kind: Service
metadata:
  name: {{ include "sudoku.fullname" . }}
  labels:
    {{- include "sudoku.labels" . | nindent 4 }}
spec:
  ports:
  - name: postgresql
    port: {{ .Values.image.port }}
    protocol: TCP
    targetPort: {{ .Values.image.port }}
  sessionAffinity: None
  type: ClusterIP
  selector:
    {{- include "sudoku.selectorLabels" . | nindent 4 }}
