node {
   def mvnHome
   stage('Prepare') { // for display purposes
      git '$SUDOKU_GIT_URL'
      mvnHome = tool 'Maven'
      if (!isUnix()) {
          error "Builds on Windows are not supported."
      }
   }
   stage('Build') {
      withEnv(["MVN_HOME=$mvnHome"]) {
        sh '"$MVN_HOME/bin/mvn" -Dmaven.test.failure.ignore --projects sudoku-lib,sudoku-svc clean install'
      }
   }
   stage('Scan') {
//       dependencyCheck additionalArguments: '', odcInstallation: 'Dependency Check'
   }
   stage('Archive') {
      archiveArtifacts 'sudoku-svc/target/*.jar'
   }
   stage('OpenShift Image Build') {
      withEnv(["PATH=${tool 'oc_cli'}"]) {
         openshift.withCluster('ocp4.home.glroland.com') {
            openshift.withProject('sudoku-build') {
               openshift.delete('buildconfig', 'abc', '--cascade')
               openshift.delete('imagestream', 'abc', '--cascade')

               openshift.newBuild('java:latest', '--name=abc', '--binary') {
                  openshift.startBuild('abc', '--from-file=sudoku-svc/target/sudoku-svc-1.0.jar', '--wait')
               }
            }
         }
      }
   }
}
