apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sudoku.fullname" . }}
  labels:
    {{- include "sudoku.labels" . | nindent 4 }}
data:
  application.properties: |-
    gamelog.url=http://log-svc:8080
    gamelog.failOnError=false
