class SudokuOCRConstants:

    SUDOKU_MODEL_FILE = 'sudoku_digit.model'

    SUDOKU_GRID_WIDTH = 9
    SUDOKU_GRID_HEIGHT = SUDOKU_GRID_WIDTH

    SUDOKU_OCR_DIGIT_WIDTH = 28
    SUDOKU_OCR_DIGIT_HEIGHT = 28
    SUDOKU_OCR_DIGIT_PAD_PERCENT = 5
    SUDOKU_BLANK_THRESHOLD = 0
    SUDOKU_MIN_PADDING = 5
