replicaCount: 1

image:
  name: app
  port: 8080

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 8080

ingress:
  annotations: {}
  url: apps.ocp4.home.glroland.com
  path: /
  tls: []

#resources: 
#  limits:
#    cpu: 1000m
#    memory: 256Mi
#  requests:
#    cpu: 500m
#    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
