replicaCount: 1

image:
  name: app
  port: 8080

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  annotations: {}
  url: apps.ocpprod.home.glroland.com
  path: /
  port: 443

resources: 
  limits:
    cpu: 2000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  target:
    type: Utilization
    averageUtilization: 80

securityContext:
  allowPrivilegeEscalation: false
  privileged: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL

podAnnotations:
  sidecar.istio.io/inject: 'true'
