apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sudoku.fullname" . }}
  labels:
    {{- include "sudoku.labels" . | nindent 4 }}
data:
  application.properties: |-
    # quarkus application configuration
    quarkus.package.type=uber-jar
    quarkus.http.port=8080
    quarkus.swagger-ui.always-include=true

    # datasource configuration
    quarkus.kubernetes-service-binding.services.my-db.api-version=postgres-operator.crunchydata.com/v1beta1
    quarkus.kubernetes-service-binding.services.my-db.kind=PostgresCluster
    quarkus.kubernetes-service-binding.services.my-db.name={{ .Release.Name }}-db
    quarkus.datasource.db-kind=postgresql
    #quarkus.hibernate-orm.database.generation=drop-and-create
    quarkus.hibernate-orm.database.generation=update
