apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: {{ include "sudoku.fullname" . }}-db-binding
spec:
  services: 
    - group: postgres-operator.crunchydata.com
      version: v1beta1
      kind: PostgresCluster 
      name: {{ .Release.Name }}-db
  application: 
    name: {{ include "sudoku.fullname" . }}
    group: apps
    version: v1
    resource: deployments
