apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-08T19:09:50Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:application.properties: {}
    manager: Mozilla
    operation: Update
    time: "2021-07-08T19:09:50Z"
  name: sudoku-log-svc-config
data:
  application.properties: |-
    # quarkus application configuration
    quarkus.package.type=uber-jar
    quarkus.http.port=8080
    quarkus.swagger-ui.always-include=true

    # datasource configuration
    quarkus.datasource.db-kind = postgresql
    quarkus.datasource.username = sudoku
    quarkus.datasource.password = password1
    quarkus.datasource.jdbc.url = jdbc:postgresql://postgresql:5432/sudoku_db
    #quarkus.hibernate-orm.database.generation=drop-and-create
    quarkus.hibernate-orm.database.generation=update
